### ISSUE TITLE
Zeeland

### ISSUE THREAD

**Issue by Barblo1986** [robertraaijmakers/com.trashchecker#103]
Hi, the app has a nice picture of the Zeeland cleaning service (ZRD) in the Homey store, but it is not supported. Can it be added?

**Comment by robertraaijmakers** [comment]
Hi, yeah they can probably be added. Depending on their digital possibilities.
Ways on how to add new API's can be found here:  https://github.com/robertraaijmakers/com.trashchecker/tree/beta/developers

**Comment by robertraaijmakers** [comment]
They seem to use one of the standard API's so I added them. Can't test it yet since the Homey Trashcan settings page seem to be broken. Hope Homey will respond to this issue soon: https://github.com/athombv/homey-apps-sdk-issues/issues/159.

**Comment by Barblo1986** [comment]
Thanks :), then we'll wait for Homey to fix the recycle bin problem???? If you want to test then of course I want to help with this and let me know!

**Comment by robertraaijmakers** [comment]
Hi @Barblo1986,

Homey has clarified what was wrong and I've updated the app accordingly.
The new version can be tested (only if you have Homey v5 installed (beta)), because the app has been completely rebuild since the latest public version due to Homey v5 and the new requirements.

The version is published to: https://homey.app/nl-nl/app/com.trashchecker/Afval-Herinnering-2.0/test/

Let me know if this works for you.

**Comment by Barblo1986** [comment]
Hi @robertraaijmakers 

Have now set Homey to update to V5 and then I will install your test app and try further. You will hear from me;)

**Comment by Barblo1986** [comment]
Hey, tested it for a few weeks now and works perfectly :)
