### ISSUE TITLE
afvalkalender.meerlanden.nl collected tag stay on nothing

### ISSUE THREAD

**Issue by ruudmens** [robertraaijmakers/com.trashchecker#11]
I installed the app for the first time last week, but somehow it seems to miss the collect days.

Picture say more than words: 
The trash settings, as you can see the first pickup that is retrieved is 29-12-2017
![trash_2](https://user-images.githubusercontent.com/20253186/34294994-4f14b218-e70b-11e7-9e60-a89d36215de0.JPG)

But at the Meerlanden afvalkalender, today the old paper is collected and 2 days ago the normal trash. Both were missed by the app
![meerlanden](https://user-images.githubusercontent.com/20253186/34294845-af107a86-e70a-11e7-9493-32c38273c29e.JPG)

The collected tag is empty for today, but should contain "papier" for today
![flow](https://user-images.githubusercontent.com/20253186/34294840-ad59afaa-e70a-11e7-8bd1-8c85b48c09a9.JPG)

**Comment by robertraaijmakers** [comment]
Thanks, will have a look into this. The today value is often not returned by the API (in this case meerlanden) and is often stored in the cache of apps , probably the one on your phone. That's why the refresh of the trash API's is only once a week in the weekend...

So it should start working at 29th of december. You can see that the value of old paper is not returned by the API in the first screenshot that you provided. I will double check on the 29th for the Meerlanden API if the values of GFT are still in there.

**Comment by robertraaijmakers** [comment]
Implemented a fix to cache the data for a week in the app. Will submit it to the store somewhere next week.
