### ISSUE TITLE
Mijn postcode wordt niet meer herkend

### ISSUE THREAD

**Issue by henkbart** [robertraaijmakers/com.trashchecker#137]
Hallo Robert,
Maak al hel lang gebruik van jouw App.
Heb een nieuwe Homey Pro en het blijkt dat hij mijn postcode niet meer vindt.
Bijgevoegd een screenshot van de ingevoerde zaken.
Heeft altijd prima gefunctioneerd. Alleen nu geeft hij steeds aan dat de postcode onbekend is.
Kan jij mij misschien verder helpen??
![59175](https://user-images.githubusercontent.com/54221226/148066613-2788c12c-9b44-4b31-9737-70cc7baa1216.jpg)

**Comment by GitMike1233** [comment]
I have the same problem as henkbart.
Homey says nothing, even if the debug info in the app.
A restart of yje app or Homey didn't help.

Can you fix it?
Please.

**Comment by robertraaijmakers** [comment]
Hi, it seems they have changed their login method. It is quite hard to get the right cookies now (it already was hard, but they even made it harder). I don't know who implemented this, but hopefully that person will return and might be able to fix it.

**Comment by GitMike1233** [comment]
Thanks for youre reaction.
I hope you can fix it with the right API or the right login method.

**Comment by GitMike1233** [comment]
Hello Robert. I did find a link were you can put in your zipcode and then you get the calender on the screen of the pc.
Maybe this wil help. I have no idea how it works.
https://afvalkalender.circulus-berkel.nl/adres/7425PE:38/ophaaldatums
Don't  know if this is helpfull.

**Comment by robertraaijmakers** [comment]
Oh that is great news!! I hope this is some official feed, because the old one is hard to implement and this is the same kind of API that is being used by 80% of the other trash vendors in the Netherlands.

I just implemented this new API, and it is available to test here: https://homey.app/nl-nl/app/com.trashchecker/Afval-Herinnering-2.0/test/

Hopefully the changes will soon be publicly available.

**Comment by GitMike1233** [comment]
Robert, i just installed the update to version 3.1.4 and after entering my zipcode an number
i get a green line that the adres is changed to the new adres.
If i test the flow i get a red checkmark, because tomorrow there is no trash. If i change to NOT in the flows
then Homey say Tomorrow is no trash.
I think that it is working ok for now. I have to wailt til tomorrow.
Thank you for your support.
And i just bought you a beer.

**Comment by henkbart** [comment]
Hello,
With the version 3.1.4 everything is working again. THANK YOU!!!!!!
Henk

**Comment by robertraaijmakers** [comment]
Thank you for the swift feedback and donation. I will close this issue :)
