### ISSUE TITLE
Afvalkalender RD4 (NL) not working anymore

### ISSUE THREAD

**Issue by R73S** [robertraaijmakers/com.trashchecker#146]
Since a couple of weeks the app is not working anymore.
In the configuration I can see the dates of collection garbage. I.e. today is 8 june 2022. The paper and garbage are collected today.
That is correct. But when the flow gives a message of what is being cvollected today, it says NOTHING.
I removed the app and installed it again. But still te problem is there.

**Comment by robertraaijmakers** [comment]
Can you please let me know which version of the app and which version of Homey you are running?

**Comment by R73S** [comment]
Hi Robert,

thank you for the fast response.
Of course I can.

"Afval Herinnering 2.0" >>> version 3.1.13
Homey >>> version 7.4.1

Thanks in advance.
Ron



Op wo 8 jun. 2022 19:11 schreef Robert ***@***.***>:

**Comment by robertraaijmakers** [comment]
Thanks! I will have a look at it.

**Comment by robertraaijmakers** [comment]
So I tried to figure out what it could be, but couldn't pinpoint the issue just yet.

You say that in the settings screen you can see that the paper and garbage are collected. Where can you see that, and can you post a screenshot? ( I know it was yesterday - but the current data will still be relevant )

Next thing you say is that the flow says that nothing is collected. Do you mean that the "And" card fails? Or do you mean that the Tag was incorrect? If the latter, can you please post a screenshot of the tags?

It is best if you can provide the data if trash is being collected in the upcoming three days, because then at least one of the tags should contain something like 'the day after tomorrow ... is being collected'.

**Comment by R73S** [comment]
I installed version 15.

When you goto APPS and open the app and goto CONFIGURE APP,  you can make
settings of the app and you can see all the dates of the RD4 calendar.
I attached 2 screenshots with the data of 8-6-2022 that was not triggered.
And 1 screenshot of 10-6-2022 that should be triggered today for collection
tomorrow. Also the screenshot of the AND card that fails.
[image: PMD 10-6-2022.jpg][image: Garbage 8-6-2022.jpg][image: Paper
8-6-2022.jpg][image: And fails.jpg]

Here's the flow AND card specified.

[image: SomethingCollectedTomorrow.jpg]

I created a flow that checks if today or tomorrow or after tomorrow
something is collected. The cards all fail.

[image: TodatTomorrowAfterTomorrow.jpg]
Here a flow that makes a log record if something is collected today or
tomorrow or after tomorrow. All say NOTHING (NIETS) is collected.
[image: FlowLogRegistration.jpg]

It seems like every situation is going into the NOTHING parameter:
[image: NothingConfiguration.jpg]

I hope this is enough to solve it. If you need anything else, please let me
know.

Op do 9 jun. 2022 om 19:40 schreef Robert ***@***.***>:

**Comment by robertraaijmakers** [comment]
Thanks for the reply! However the images won’t load since image upload by replying on email is not supported on GitHub. Can you upload the images through the web interface?

**Comment by R73S** [comment]
![And fails](https://user-images.githubusercontent.com/82821342/172932027-1d932524-b14c-4a91-83f1-af032b624f44.jpg)
![Garbage 8-6-2022](https://user-images.githubusercontent.com/82821342/172932271-34677dda-0a81-48d7-a21b-bcc0a53dd951.jpg)
![Nothing](https://user-images.githubusercontent.com/82821342/172932283-a1da6b11-5ef0-49d4-9892-9732dbbd1527.jpg)
![NothingCollected](https://user-images.githubusercontent.com/82821342/172932287-abf5fd87-2c52-4d48-b44a-c72a4faf016f.jpg)
![NothingConfiguration](https://user-images.githubusercontent.com/82821342/172932289-1e8b9f69-be61-4f76-84dc-77ce2e2f166b.jpg)
![Paper 8-6-2022](https://user-images.githubusercontent.com/82821342/172932293-45029c62-7c28-43ba-ba93-1322b5678f6d.jpg)
![PMD 10-6-2022](https://user-images.githubusercontent.com/82821342/172932294-4e9b9cbb-92a5-4573-befa-01fc4cddd4c9.jpg)
![SomethingCollectedTomorrow](https://user-images.githubusercontent.com/82821342/172932297-264ee421-ec72-4cfb-921d-ff013590a365.jpg)
![TodatTomorrowAfterTomorrow](https://user-images.githubusercontent.com/82821342/172932300-87b45a57-49a1-4bd1-a2f3-72a8f5725a2f.jpg)

**Comment by robertraaijmakers** [comment]
Thanks, that was it. The dates retrieved are in the dd-mm-yyyy format instead of yyyy-mm-dd. It seems that the developers behind RD4 like to turn them around once in a while, but I thought I had mitigated that issue already.

New version is live and when you retrieve the new dates they should be in the right format and things should start working again!

**Comment by R73S** [comment]
Great! It works again. Thank you for the fast support!
