### ISSUE TITLE
Ghost flow triggers

### ISSUE THREAD

**Issue by iisworks** [robertraaijmakers/com.trashchecker#155]
When using an advanced flow, I am seeing daily "ghost" notifications at times no flow is supposed to be triggered.

Flow (note  it starts at 9AM for what gets collected tomorrow):
![image](https://user-images.githubusercontent.com/33196233/187068709-0fdb1332-2d9c-49a8-9e3a-bf8c1645de13.png)

I get notifications that do not make sense: it appears maybe once a day at a random time and mentions "Today", so it is clearly not triggered by that flow:
![image](https://user-images.githubusercontent.com/33196233/187068765-59978b11-9bba-48c8-a540-697c2acc3754.png)

I am 100% sure there is no other flow referencing the app, and it used to work fine in a regular flow. 
I am using advanced flows exclusively now, and I have seen no issues otherwise.

Any clue what could cause this?

**Comment by robertraaijmakers** [comment]
We’ve seen some more issues with advanced flows coming in. Most of them are related to the advanced flow itself and not so much the app.

if you have multiple triggers, and get more notifications, it means that the flow is triggered more often then it should. Because it should only trigger at 9. You can better log this issue at Athom to see why your flow it getting triggered randomly.

**Comment by iisworks** [comment]
I have many triggers for other apps as well, but somehow this is the only one this happens with.
Also note it's not this flow that triggers, because the condition is about Tomorrow and not today. 

Anyway, I'll open a case with AtHom if the issue persists.
