### ISSUE TITLE
Recycle! App BE not working

### ISSUE THREAD

**Issue by Didiervu91** [robertraaijmakers/com.trashchecker#157]
Since a few weeks the Belgium version stopped working. Re-entering the address info gives me “Dit adres wordt niet ondersteund”. Although it always worked.

I see online that I have to fill in my city name also behind the postal code, perhaps this could be the problem?

**Comment by KRens** [comment]
I confirm having the same issue.
Used to work, but no updates anymore.
Adress is not supported.

**Comment by objt-ev** [comment]
#debugged via developer console... recycleapp API's have been moved to another server this month + they have a new root path...
The api calls themselfes and their response did not changed.

I have prepared the changes in a seperate branch and issued a PR

**Comment by robertraaijmakers** [comment]
Thanks to @objt-ev there is a version available where this issue is fixed, it can be tested here: https://homey.app/nl-nl/app/com.trashchecker/Afval-Herinnering-2.0/test/

**Comment by Didiervu91** [comment]
> Thanks to @objt-ev there is a version available where this issue is fixed, it can be tested here: https://homey.app/nl-nl/app/com.trashchecker/Afval-Herinnering-2.0/test/

Same issue (address not supported). Perhaps something to do with the POST / GET request?

**Comment by objt-ev** [comment]
indeed, they changed one request from a GET to a POST...
tested that one in a separate environment and it works again...


-------- Oorspronkelijk bericht --------
Van: Didiervu91 ***@***.***>
Datum: 14/12/2022 23:14 (GMT+01:00)
Aan: "robertraaijmakers/com.trashchecker" ***@***.***>
Cc: Erwin Vervondel ***@***.***>, Mention ***@***.***>
Onderwerp: [EXTERNAL] Re: [robertraaijmakers/com.trashchecker] Recycle! App BE not working (Issue #157)


EXTERNAL
________________________________


Thanks to @objt-ev<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fobjt-ev&data=05%7C01%7Cerwin.vervondel%40aptean.com%7C25d88f6c89a84a6c65b008dade208b38%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638066528614220012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mS3QNe4qJEJgCV73EfxZpifustbOqCRvYxOlOUk2YLs%3D&reserved=0> there is a version available where this issue is fixed, it can be tested here: https://homey.app/nl-nl/app/com.trashchecker/Afval-Herinnering-2.0/test/<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhomey.app%2Fnl-nl%2Fapp%2Fcom.trashchecker%2FAfval-Herinnering-2.0%2Ftest%2F&data=05%7C01%7Cerwin.vervondel%40aptean.com%7C25d88f6c89a84a6c65b008dade208b38%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638066528614220012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LU7Bld1yRx4Ki2Oif2fThzG3On8wRKOsX5wE7B%2FHmwQ%3D&reserved=0>

Same issue (address not supported). Perhaps something to do with the POST / GET request?

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frobertraaijmakers%2Fcom.trashchecker%2Fissues%2F157%23issuecomment-1352289659&data=05%7C01%7Cerwin.vervondel%40aptean.com%7C25d88f6c89a84a6c65b008dade208b38%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638066528614220012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4cJ4CzAT9btCoO5EtDqYHye1LPznWwYxE5FRoWD0Zgc%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMQEAWTQNDDP5HWL3JOLFILWNJBDTANCNFSM6AAAAAARVY5NJQ&data=05%7C01%7Cerwin.vervondel%40aptean.com%7C25d88f6c89a84a6c65b008dade208b38%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638066528614220012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8DPL0uE5AE416hc%2B1l3WtHP6gLshBSIk7MkZUrjbjrA%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

This message contains information that is confidential and/or may be privileged. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution or copy of this message and/or its attachments is strictly prohibited. If you have received this message in error, please advise the sender immediately by replying to this email and delete this message. We are committed to your privacy. For more information, please see our Privacy Policy at https://www.aptean.com/privacy-statement

**Comment by robertraaijmakers** [comment]
Thanks! New version for test here: https://homey.app/a/com.trashchecker/test/

**Comment by objt-ev** [comment]
Hierbij kan ik bevestigen dat recycle app koppeling terug werkt !!

Mvg,
Erwin

From: Robert ***@***.***>
Sent: 16 December 2022 09:21
To: robertraaijmakers/com.trashchecker ***@***.***>
Cc: Erwin Vervondel ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [robertraaijmakers/com.trashchecker] Recycle! App BE not working (Issue #157)

EXTERNAL
________________________________


Thanks! New version for test here: https://homey.app/a/com.trashchecker/test/<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhomey.app%2Fa%2Fcom.trashchecker%2Ftest%2F&data=05%7C01%7Cerwin.vervondel%40aptean.com%7Cbbf19c95419648591da008dadf3e82dd%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638067756840592793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t1rrB0icyvV4KqoH1wUlkATg00qZlI62YYy%2Fvxp8aRE%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frobertraaijmakers%2Fcom.trashchecker%2Fissues%2F157%23issuecomment-1354373988&data=05%7C01%7Cerwin.vervondel%40aptean.com%7Cbbf19c95419648591da008dadf3e82dd%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638067756840592793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nAVJ%2BrKqSe%2BYshzhzqWMSe4Jf%2BxdSO7iqRayLZSYNrw%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMQEAWT5GIYVUQKSZWTVLC3WNQQ77ANCNFSM6AAAAAARVY5NJQ&data=05%7C01%7Cerwin.vervondel%40aptean.com%7Cbbf19c95419648591da008dadf3e82dd%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C638067756840592793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Uumo3EDySK1sVXKWPa8sBr7jtLBoufngwwHPVHKGEp4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

This message contains information that is confidential and/or may be privileged. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution or copy of this message and/or its attachments is strictly prohibited. If you have received this message in error, please advise the sender immediately by replying to this email and delete this message. We are committed to your privacy. For more information, please see our Privacy Policy at https://www.aptean.com/privacy-statement
