### ISSUE TITLE
RD4 address is not supported (Homey Pro '23) but works on (Homey Pro Early '19)

### ISSUE THREAD

**Issue by stofferr** [robertraaijmakers/com.trashchecker#168]
Hi,
I am migrating my Trashcan Reminder from Homey Early 2019 to Homey Pro '23.
On '19 it works with 6471CD 57 / RD4, however, when I use the same settings on '23 it reports "Address is not supported".
Is this a bug with the app, or with HP23? If App I hope this can be resolved.
Thanks

**Comment by robertraaijmakers** [comment]
I have no clue, I see some more errors (also on other apps) coming in with Homey Pro '23.
I don't know what's up with the new Homey Pro and what has changed under the hood and as I don't have the money to buy one I won't be able to test it. So hope someone else can debug the app and see what has changed in Homey Pro '23 that kills the app.

**Comment by stofferr** [comment]
Hi Robert,
Yup - still exists :(
Thanks for checking.
BTW: I have requested Athom to provide you with a free Homey Cloud, and I
mentioned you and your App specifically.
Let's see what happens.....
Roger

**Comment by robertraaijmakers** [comment]
Thanks, I found the issue. The API now requires the house number extension otherwise it would tell that the address cannot be found.

I have added a fix in code, but can't deploy it. It seems that Athom have revoked registering new development machines to their store API so I cannot publish the new version... will let you know once they allow new machines to be registered again.

**Comment by stofferr** [comment]
Dankje Robert.
Intussen heb ik de suggestie gedaan om geregistreerde ontwikkelaars tenminste een gratis Homey Cloud te geven.
Roger

⁣Get BlueMail for Android ​

**Comment by stofferr** [comment]
Works - I can now add our address.
Thanks!
