### ISSUE TITLE
Feature request: Add an additional date: 'Yesterday'

### ISSUE THREAD

**Issue by khuizer** [robertraaijmakers/com.trashchecker#188]
I've used the trashchecker to display on my dashboard (and push notification) that the trash will be picked up tomorrow / today. 

But I would also like to have a 'When' action for 'Yesterday', that way I can send a push notification reminder to myself to get the kliko from the streets.

**Comment by robertraaijmakers** [comment]
Hi, best is to sent yourself a reminder on the same day before going to bed, or, when you have location enabled, to sent it the same day when you arive at home.

The reason for not adding "yesterday" is because the dates are getting cleared by the API when retrieving new ones and thus dates in the past might get lost and people will then start complaining that the functionality doesn't work.

There are two options to overcome this 'missing' feature:
- In the flow that puts the trash out, add some kind of wait condition for x-hours / a day, before sending you a push notification
- Give yourself a notification on the day the trash is collected, e.g. in the evening at 22:00, or when arriving home. Please note that it is advised to get the bin the same day (https://vuilnisbakinfo.nl/tips/hoe-laat-mag-de-kliko-buiten-staan/#Hoe_lang_mag_je_de_Kliko_laten_staan)
