### ISSUE TITLE
All dates are 1 day early

### ISSUE THREAD

**Issue by Veldkornet** [robertraaijmakers/com.trashchecker#28]
App: v2.4.1, v2.3.3
Homey: 1.5.12

The app has been running flawlessly for months, but for the past 2 weeks (I assume nothing to do with the winter time change??), my flows are all being triggered 1 day early, and on the actual day.

FYI, I just have a flow that says IF something is being picked up today, send a message with what's being picked up.

The problem is, when I look on the debug panel in settings, I only see the dates that are 1 day early; but when I look on the MijnAfvalwijzer website, they do show the correct day.

I have no idea why all of a sudden they are all one day earlier, or why it still triggers on the correct day as well....

**Comment by Veldkornet** [comment]
I checked the debug log in v.2.4.4.

And the dates mentioned are indeed shown as one day early.

"REST": [
    "28-11-2018",
    "12-12-2018",
    "27-12-2018"
  ]
}

Although the REST should be 29-11-2018. I will check again tomorrow, but I assume that tomorrow it will show the dates of 1 day later (ie, tomorrow).

**Comment by Veldkornet** [comment]
Right so I checked again today, and I did get a notification again today that the trash was being picked up, however in the debug log, it still shows the dates that it had yesterday:

```
{
"REST": [
    "28-11-2018",
    "12-12-2018",
    "27-12-2018"
  ]
}
```

FYI, this is my flow. As you can see, it only checks for things that are scheduled for today. so... I don't know whats going on or why I get the notification twice (once on the day before, and once on the correct day)..

![image](https://user-images.githubusercontent.com/10297361/49244618-830b2580-f410-11e8-86bb-fe4bb1f31581.png)

**Comment by robertraaijmakers** [comment]
This is really strange! I'm having issues myself with the pick up dates because half the time I won't get a message at all. Maybe your Homey is compensating on the messages that I miss...

What you can try to do is remove or disable this flow and see if you still get messages. Maybe there is some second flow that triggers on another day? Or a ghost flow somewhere in Homeys memory?

I will check to see if the dates stored are somehow parsed to a valid JavaScript datetime object and that something is happening there...

**Comment by jalbrink** [comment]
App version: 2.3.3
Homey: 1.5.13

I'm having the same issue as @Veldkornet. I also have a flow that triggers when something is picked up today. The notification comes one day early. When i change it to tomorrow it works correctly. It seems like tomorrow and today have the same value internally as @Veldkornet  mentions. Any solutions yet?

**Comment by jalbrink** [comment]
It seems it's taking the 2019 dates of mijn Afvalwijzer. Those happen to be 1 day early for 2018

**Comment by robertraaijmakers** [comment]
I've checked and indeed mijn afvalwijzer API doesn't provide an option to see which year the dates are in. They only publish the dates and not the year. So as this does explain the issue of @jalbrink it doesn't explain the issue that @Veldkornet is experiencing since the debug dates are the dates that should be used to check against.

**Comment by Veldkornet** [comment]
As of 27-12-2018 (the date from above that was the only correct one), everything seems to be back to normal and working again. Notifications are only received on the actual day as expected...
