### ISSUE TITLE
No new dates

### ISSUE THREAD

**Issue by hans70** [robertraaijmakers/com.trashchecker#37]
405GL, 14
Since the new year there are no new dates available Although the source afval app supports the adres.
On the site of afval app the current dates are shown. 
Maybe it's possible to integrate avri.nl as source which is our garbage collector? That way I don't have to rely on afval app as source.

Thanks in advance!

**Comment by robertraaijmakers** [comment]
Can you check the beta version of the app? This has an updated version of the afval app.
If you want to implement the avri.nl site you are more than welcome to contribute. I'm not implementing any new API's since they break all the time and are costing a lot of time to maintain.

If the API's won't work for you you can also try to use the manual option. This suits almost all pick-up schemes.

**Comment by hans70** [comment]
Hi Robert,
I'll, have a look if I can install the beta this weekend. I'm still trying to get used to new homey app. 
Thanks for replying!

**Comment by robertraaijmakers** [comment]
Should work again with 2.5.2
