### ISSUE TITLE
ACV

### ISSUE THREAD

**Issue by Bozo29** [robertraaijmakers/com.trashchecker#42]
We changed a Month of 2 ago to the ACV.
This app doesn’t support it.
Van you please implement ACV in the app?

**Comment by robertraaijmakers** [comment]
Sorry, the ACV implementation is completely different from the other implementations and will cost some time to implement. As described in the description of the app I won't maintain or add any (new) API's since I can make a fulltime job out of it. Maybe you can find someone living in your area with programming skills that can add it or use the manual option to still give you notifications when the trash is collected.

**Comment by robertraaijmakers** [comment]
I'm happy to announce that ACV support is added as of version 2.6.3!
