### ISSUE TITLE
Afvalwijzer does not work

### ISSUE THREAD

**Issue by jeroenvano** [robertraaijmakers/com.trashchecker#45]
The app gives an error saving the postcode and house number "Dit adres wordt niet ondersteund" on the mijnafvalwijer. 

On the website of mijnafvalwijer the postcode and house number work.

This app used to work but it seems that after an update it stopped working for my address.

Postcode 5345

**Comment by fspaan** [comment]
**What I tried to do**
Installed Afvalwijzer 2.0 for Homey 2.04.  I entered postcode and housnumber with source: 'Mijn Afvalwijzer'. However, I received an error message: 'Dit adres wordt niet ondersteund'. Upon checking the website mijnafvalwijzer, I noticed the postcode has to be entered in the following format <9999>[blank spac]<XX>. (Example 1234 AA). I noticed that the field does not support this in the configuration of the Homey App.

**Steps I have taken**
Installed Afvalwijzer 2.04. Chose 'Configureer App', Entered postode 1234AA, housnumber 1 (example), country NL, source: Mijn Afvalwijzer.

**System I use**
Homey 2.04, Afvalwijzer 2.0. (Previously I used the 1.5 version.

**Advise**
Please check entryfield Postcode. In the homeyapp a different format is required and does not match the format of Mijnafvalwijzer. 
In the Homey App: Format: 1111AA
In the Afvalwijzer: format: 1111 AA

Thanks

**Comment by AnonymousMiz** [comment]
Diagnostic report code: ac1bca21-00a3-449d-b33e-20b98754ea05

**Comment by Veldkornet** [comment]
I have the same issue

**Comment by uNiiek** [comment]
I also have the problem with "Mijn Afvalwijzer"

**Comment by A333333** [comment]
Me too, “dit adres wordt niet ondersteund”  but website Afvalwijzer works. Also the data which is already collected is correct. But no triggers are working. It was working before.
It always worked like it is supposed to be.

**Comment by larsnet** [comment]
Same issue

**Comment by maikrovers** [comment]
There is defenitly an issue with the app. I receive the same message.

**Comment by robertraaijmakers** [comment]
All, sorry for not replying earlier. I'm currently not able to investigate this. I'm will happily accept a pull request and push that to the Athom store when someone provides a fix.

**Comment by Veldkornet** [comment]
Is it possible that it’s because the app is requesting via HTTP but the site is now in HTTPS by default? I don’t know if it has always been this way...

I looked in your code and saw that you use 
http://www.mijnafvalwijzer.nl/nl/

But if I just do a simple cURL to that URL, I get a 301 permanently moved. But if I do a cURL to 
https://www.mijnafvalwijzer.nl/nl/
Then I get a 200OK response.

**Comment by A333333** [comment]
Hi Robert,

I honestly don’t know if it is suddenly only https.
I just select the proper waste calender. I cannot adjust it in something else because it is coded.

I forgot my wastebins already 1 time since Homey could not tell me to put the containers to the collection point...

I think this needs some work in your app?

Thanks in advance and for your good work so far!




Verstuurd vanaf mijn iPhone X

Op 22 mrt. 2019 om 18:02 heeft Veldkornet <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Is it possible that it’s because the app is requesting via HTTP but the site is now in HTTPS by default? I don’t know if it has always been this way...

I looked in your code and saw that you use
http://www.mijnafvalwijzer.nl/nl/

But if I just do a simple cURL to that URL, I get a 301 permanently moved. But if I do a cURL to
https://www.mijnafvalwijzer.nl/nl/
Then I get a 200OK response.

**Comment by robertraaijmakers** [comment]
Thanks to @Veldkornet a new version of the app is submitted to Athom. After review it will soon hit the store as beta and when feedback is good I will push it to master.

**Comment by larsnet** [comment]
I installed the beta from the app store.
Afvalwijzer is working for me again , Thanks!

**Comment by robertraaijmakers** [comment]
2.5.3 is released as public version. Should all work now. Closing this issue.
