### ISSUE TITLE
The "Any"label does not work

### ISSUE THREAD

**Issue by mennetalsma** [robertraaijmakers/com.trashchecker#65]
Robert

Here's my simple flow. At 19:00 the flow checks if there is a waiste-collection scheduled for the day after and it announces the results through the speaker.

it works perfectly when Paper, Residual or Organic waiste is scheduled. But when nothing is scheduled for 'tomorrow', the collected-label (see pic) gets filled with the value "Nothing is collected today" 

So every day, Homey notifies me that NOTHING IS C0LLECTED! :-) whilst I only need a notification when something actually is scheduled (so i dont forget) I would like the app (and Homey) to stay silent if no trash is collected.

![image](https://user-images.githubusercontent.com/9373953/66996500-21f44b00-f0d1-11e9-9fcd-753b37d0804c.png)

regards
Menne

**Comment by robertraaijmakers** [comment]
Hi Menne,

Thanks for making the screenshot and providing the details. I have (almost) exactly the same flow. Only mine checks in the "and" column for any trash collected **today**. Can you check if you change the " and" statement to **today** and test the flow if it still tells you that nothing is collected?

Because your labels tells you that " nothing is collected today " . Which is actually true, because the statement checks for tomorrow. It still doesn't explain why you get the message everyday.

So lets do some other troubleshooting. If you go to the App Settings page. Have you configured the labels as follows?
![Screenshot 2019-10-17 at 20 25 20](https://user-images.githubusercontent.com/1773099/67036736-6eb14380-f11c-11e9-8adf-ef3ce4322aad.png)

Another good thing to check is the following, are any dates filled in here?
![Screenshot 2019-10-17 at 20 27 04](https://user-images.githubusercontent.com/1773099/67036786-8688c780-f11c-11e9-896c-37bb7688a263.png)

So if you can check if the labels are set correctly, the dates are filled according to the dates that your trash should be picked up. Please let me know if then still doesn't work.

If it still doesn't work please let me know:
- Which app version are you using?
- Which Homey software version are you running on?
- Does changing the check to " today " work ?

**Comment by robertraaijmakers** [comment]
Did it work?
