### ISSUE TITLE
Oud papier

### ISSUE THREAD

**Issue by jalbrink** [robertraaijmakers/com.trashchecker#70]
I would like to add a feature request. In our village 'oud papier' is collected at specific dates that don't match a particular pattern. Once a year we get a list of dates when it will be collected. It would be nice to be able to add a manual list of dates for a certain trash type. The rest of the trash types works perfect with automatic dates.

**Comment by robertraaijmakers** [comment]
Hi, what do you mean with "automatic dates"? As in, is part of the trash dates being retrieved through an API?

Does this mean that you have multiple parties collecting trash in your city?

If you give an example zipcode + house number I can maybe check to see if the paper dates are also added to the API and can be retrieved automatically.

**Comment by jalbrink** [comment]
Yes with automatic dates I mean the dates imported by the Afvalwijzer API for my zip code. And yes 'oud papier' is not collected by the same party as the rest.

**Comment by robertraaijmakers** [comment]
In version 2.7.0 I've added the option to overwrite the API dates based on patterns. This can be done by the "manual" option where you can enter a pattern. Default values are "based on API" but you can overwrite this.

Sorry if the dates that the trash is collected is completely random, because then this won't solve your specific issue. But hopefully there is some sort of pattern in the dates that you got.
