### ISSUE TITLE
[feature request] trash is outside

### ISSUE THREAD

**Issue by ZimoSka** [robertraaijmakers/com.trashchecker#87]
Hello, this is really great app.

I have created several workflows which are spamming me about trashcan (because one reminder is unfortunately not enough for me).

It will be nice to have possibility to tell app, that trashcan is outside prepared for pick up and no further notification will come. I can do it via virtual device or variable, however it will be nice to have it in app.

Thanks.

**Comment by robertraaijmakers** [comment]
Hi,

Thanks for reporting this and very happy to hear that the app works great. I don't see how the app can do an easier implementation then assigning a variable through the default out-of-the-box possibilities. So I will close this issue since a variable is a perfect way of handling this.

With kind regards.
